sudo: false

language: bash

services:
  - docker

before-script:
  - docker -v
  - docker-compose  -v
  - set -e

jobs:
  include:
    - stage: build-and-push
      script:
        # build
        - docker build -t $APP_IMAGE .
        - docker run $APP_IMAGE composer ci

        # push
        - docker pull quay.io/keboola/developer-portal-cli-v2:latest
        - >-
          export REPOSITORY=`docker run
          --rm
          -e KBC_DEVELOPERPORTAL_USERNAME
          -e KBC_DEVELOPERPORTAL_PASSWORD
          -e KBC_DEVELOPERPORTAL_URL
          quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
        - docker tag $APP_IMAGE:latest $REPOSITORY:$TRAVIS_COMMIT
        - >-
          eval $(docker run
          --rm
          -e KBC_DEVELOPERPORTAL_USERNAME
          -e KBC_DEVELOPERPORTAL_PASSWORD
          -e KBC_DEVELOPERPORTAL_URL
          quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
        - docker push $REPOSITORY:$TRAVIS_COMMIT
    - stage: integration
      script:
        - docker pull quay.io/keboola/syrup-cli:latest
        - >-
          docker run
          --rm
          -e KBC_STORAGE_TOKEN
          quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $KBC_APP_TEST_CONFIG_WITH_SAVE_AS_HTTP $TRAVIS_COMMIT
    - script:
        - docker pull quay.io/keboola/syrup-cli:latest
        - >-
          docker run
          --rm
          -e KBC_STORAGE_TOKEN
          quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $KBC_APP_TEST_CONFIG_WITHOUT_SAVE_AS_HTTPS $TRAVIS_COMMIT
    - stage: deploy
      script: ./deploy.sh
      if: tag IS present
