sudo: false

services:
  - docker

before_script:
  - docker -v
  - docker build -t keboola/ex-http .
  - docker run keboola/ex-http composer ci

script:
  - echo "Build successful"

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
