sudo: false

services:
  - docker

before_script:
  - docker-compose -v
  - docker-compose build prod
  - docker-compose run --rm prod composer ci

script:
  - echo "Build successful"

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
